version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: bookstore-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore
      MYSQL_PASSWORD: bookstore123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - bookstore-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: bookstore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bookstore-network

  # 用户端后端服务
  bookstore-backend:
    build:
      context: .
      dockerfile: Dockerfile.bookstore
    container_name: bookstore-backend
    restart: unless-stopped
    ports:
      - "8080:8080"  # 用户服务
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=bookstore
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - bookstore-network

  # 管理员端后端服务
  admin-backend:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: bookstore-admin-backend
    restart: unless-stopped
    ports:
      - "8081:8081"  # 管理员服务
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=bookstore
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - bookstore-network

volumes:
  mysql_data:
  redis_data:

networks:
  bookstore-network:
    driver: bridge 